projectDjango/customer/urls.py
from django.contrib import admin
from django.urls import path,include
from customer.views import *
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('success/', success, name='success'),
    path('reserve/', ReserveMaid.as_view(), name='reserve'), 
    path('reservemaid/<int:pkmaid>', update_reserve, name='reserve'), 
    path('viewmaid/', ListMaidView.as_view(), name='viewmaid'),
    path('viewprofile/', CustomerProfile.as_view(), name='viewprofile'),
    path('update_profile/', update_profile, name='update_profile' ),
    path('detail_reserve/', getinfo, name='detail_reserve'),
    path('slipform',SlipView.as_view(), name='slipform'),
    path('signin/', signin, name='signin'),
	path('signout/', signout, name='signout'),

    # path('rent',rent,name='rent'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectDjango/maid/urls.py
from django.contrib import admin
from django.urls import path,include
from maid.views import *
from django.conf import settings
from django.conf.urls.static import static
from maid import views


urlpatterns = [    
    path('register/', MaidRegister.as_view(),name ='register'), 
    path('profilemaid/', views.getinfomaid,name ='profilemaid'), 
    path('signupmaid/', SignUpMaid.as_view() ,name ='signupmaid'),
    path('signinmaid/', signinmaid ,name='signinmaid'),
    path('signoutmaid/', signoutmaid ,name='signoutmaid'),
    path('update_maidprofile/', views.update_maidprofile, name='update_maidprofile' ),
    # path('retereview/' ,views.retereview, name='retereview'),
    path('retereview/', RateReviews.as_view(),name='ratereviews')
 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectDjango/projectDjango/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('auth/', include('wl_auth.urls') ),
    # path('login/', auth_views.LoginView.as_view()),
    path('app/', include('customer.urls') ),
    path('maid/', include('maid.urls') ),
    

    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectDjango/customer/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.db.models.signals import pre_save,post_save
from django.dispatch import receiver
import numpy as np

class Customer(models.Model):
	user = models.OneToOneField(User,on_delete=models.SET_NULL,null=True, blank=True)
	telephone = models.CharField(max_length=10)

	def __str__(self):
		return self.user.username

@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Customer.objects.create(user=instance)

class Maid(models.Model):
	user = models.OneToOneField(User,on_delete=models.SET_NULL,null=True, blank=True)
	image_maid = models.ImageField(upload_to='picmaid',null=True,blank=True)
	address = models.CharField(max_length=100,null=True)
	telephone = models.CharField(max_length=10,null=True)

	def average_rating(self):
		all_ratings = map(lambda x: x.rating, self.review_set.all())
		return np.mean(all_ratings)

	def __str__(self):
		return self.user.username

class Review(models.Model):
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    maid = models.ForeignKey(Maid , on_delete=models.SET_NULL,null=True)
    rating = models.IntegerField(choices=RATING_CHOICES)

TYPEAREA_CHOICES=[
	('home', 'Home'),
	('condo', 'Condo'),
]

SIZE_CHOICES = [
	('less25', 'Lessthan 25 sqm.'),
	('between', 'Between 25 to 50 sqm.'),
	('morethan', 'Morethan 50 sqm.'),
]

class Reserve(models.Model):
	reserve_date = models.DateTimeField(default=timezone.now )
	cost = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True)
	typearea = models.CharField(choices=TYPEAREA_CHOICES, max_length=128, null=True)
	size = models.CharField(choices=SIZE_CHOICES, max_length=128, null=True)
	addresswork = models.CharField(max_length=200,null=True)
	datework = models.DateTimeField(default=timezone.now )
	maid_id = models.ForeignKey("Maid", on_delete=models.SET_NULL, blank=True,null=True)
	user = models.OneToOneField(User, on_delete=models.SET_NULL,null=True, blank=True)
	def __str__(self):
		return "id %s %s"%(self.id,self.maid_id.user.username)

class Money(models.Model):
	user = models.OneToOneField(User, on_delete=models.SET_NULL,null=True, blank=True)
	resever_id =  models.OneToOneField(Reserve, on_delete=models.SET_NULL,null=True)
	image_slip = models.ImageField(upload_to='slip',null=True)
	timesection = models.DateTimeField(default=timezone.now)
	price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

	def __str__(self):
		return self.user.username

projectDjango/customer/forms.py
from django import forms
from django.forms import ModelForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django.contrib.admin import widgets
import datetime
from .models import Maid, Reserve, Money, Customer
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class ReserveForm(ModelForm):
    class Meta:
        model = Reserve
        exclude = ['user','image','cost','reseerve_date','maid_id']

    def __init__(self, *args, **kwargs):
        super(ReserveForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit','Reserve'))

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        super(CustomerForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit','Register Now'))


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254,)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', 'email')
        exclude = []
        
class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('__all__')
        exclude = ['user']

class UpSlipForm(forms.ModelForm):
    class Meta:
        model = Money
        exclude = ['resever_id','user']

    def __init__(self, *args, **kwargs):
        super(UpSlipForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit','Reserve Now'))
    
class MaidForm(forms.ModelForm):
    class Meta:
        model = Maid
        fields = ('__all__')

projectDjango/customer/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from customer.forms import *
from .models import Customer, Maid, Reserve, Money
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect ,render_to_response
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy 
from django.views import generic
from django.db.models import signals
from django.contrib.auth.models import User
from django.db import transaction
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.http import HttpResponse
from django.shortcuts import render_to_response

# Create your views here.
@login_required
def success(request):
    return render(request,"success.html")
    
class SignUp(generic.CreateView):
    form_class = SignUpForm
    success_url = '/auth/signin'
    template_name = 'signup.html'

class LoginRequiredMixin(object):
    @classmethod
    def as_view(cls):
        return login_required(super(LoginRequiredMixin, cls).as_view())

class ReserveMaid(LoginRequiredMixin,CreateView):
    template_name='reserve.html'
    form_class = ReserveForm
    success_url = '/app/viewmaid'
    def form_valid(self,form):
        form.instance.user=self.request.user
        return super(ReserveMaid,self).form_valid(form)

@login_required
@transaction.atomic
def update_reserve(request,pkmaid):
        # if request.method == 'POST':
            # reserve_form = ReserveForm(request.POST, instance=request.user)
        reserve = Reserve.objects.get(user=request.user)
        idmaid = Maid.objects.get(id=pkmaid)
        reserve.maid_id = idmaid

        if reserve.typearea == 'home' and reserve.size == 'less25':
            cost = 300
        elif reserve.typearea == 'home' and reserve.size == 'between':
            cost = 600
        elif reserve.typearea == 'home' and reserve.size == 'morethan':
            cost = 1200
        elif reserve.typearea == 'condo' and reserve.size == 'less25':
            cost = 500
        elif reserve.typearea == 'condo' and reserve.size == 'between':
            cost = 800
        elif reserve.typearea == 'condo' and reserve.size == 'morethan':
            cost = 1500
        
        reserve.cost = cost
        reserve.save()
        pk = User.objects.get(username = request.user.username)
        temp = Reserve.objects.filter(user_id=pk.id)
        return render(request, 'detail_reserve.html', {'object_list':temp})


class CustomerRegis(LoginRequiredMixin,CreateView):
    template_name='register.html'
    form_class = CustomerForm
    success_url = '/app/reserve'
    def form_valid(self,form):
        form.instance.user=self.request.user
        return super(CustomerRegis,self).form_valid(form)


class CustomerProfile(DetailView):
    model = Customer
    template_name='detail_reserve.html'
    slug_field = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    
   
class ListMaidView(LoginRequiredMixin,ListView):
    model = Maid  
    template_name='display_maid.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['now'] = timezone.now()
        return context

@login_required
def	getinfo(request,pk=None):
    pk = User.objects.get(username = request.user.username)
    temp = Reserve.objects.filter(user_id=pk.id)
    return render(request, 'detail_reserve.html', {'object_list':temp})

def signin(request):
	if request.method == 'POST' and 'username' in request.POST:
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:	
			if user.is_active:
				if 'remember' in request.POST:
					if request.POST['remember']=='1':
						request.session.set_expiry(604800) #remember keep session for a week
				else:
					request.session.set_expiry(14400) #not remember keep session for 4hrs

				login(request, user)
				request.session['username'] = user.username
				
				return redirect('reserve')
			else:
				msg="Disabled account"
		else:
			msg="Invalid username or password"
		return render(request,'login.html',{'msg': msg})   
	return render(request,'login.html',{'msg': ""})

def signout(request):
	if 'username' in request.session:
		del request.session['username']
	logout(request)
	return redirect('signin')
   

@login_required
@transaction.atomic
def update_profile(request):
        if request.method == 'POST':
            user_form = UserForm(request.POST, instance=request.user)
            profile_form = ProfileForm(request.POST, instance=request.user.customer)
            if user_form.is_valid() and profile_form.is_valid():
                user_form.save()
                profile_form.save()
                messages.success(request, ('Your profile was successfully updated!'))
                return redirect('reserve')
            else:
                messages.error(request, ('Please correct the error below.'))
        else:
            user_form = UserForm(instance=request.user)
            profile_form = ProfileForm(instance=request.user.customer)
        return render(request, 'profile_update.html', {
            'user_form': user_form,
            'profile_form': profile_form})

class SlipView(LoginRequiredMixin,CreateView):
    model = Money
    form_class = UpSlipForm  
    template_name='slip.html'
    success_url = '/app/success'
    def form_valid(self,form):
        form.instance.user=self.request.user
        res = Reserve.objects.get(user=self.request.user)
        form.instance.resever_id=res
        return super(SlipView,self).form_valid(form)

projectDjango/customer/templates/detail_reserve.html
<html>
<style>
        input[type=text], select ,button{
            /* width: 100%;
            padding: 12px 20px;
            margin: 8px 0; */
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
            padding: 10px;
            margin: 5px;
        }
        input[type=password], select ,button{
            /* width: 100%;
            padding: 12px 20px;
            margin: 8px 0; */
            display: inline-block;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
            padding: 10px;
            margin: 5px;
        }
        input[type=submit] ,button{
            width: 100px;
            background-color: rgb(37, 19, 2);
            color: white;
            padding: 14px 20px;
            margin-left: auto;
            margin-right: auto;
            border: none;
            /* border-radius: 4px; */
            cursor: pointer;
            
            
        }
        
        input[type=submit]:hover,button:hover {
            background-color: rgb(6, 44, 31);
        }
        
        .register-content {
            border-radius: 15px;
            background-color:rgba(255, 255, 255, 0.87);
            padding: 50px;
            margin-left: auto;
            margin-right: auto;
            margin-top: 20%;
            width: 80%;
            padding-bottom: 30%;
         

            
            
        }
        .signin-bg{
            background-image: url("../../img/bg.jpg");
            background-repeat: no-repeat;
            background-size: cover;
            padding-bottom:90%;
            
        }
        .sign-text{
            text-align: center;
            color:#24465c;
            font-size: 5vw;
            font-style: oblique;
            padding: 0%;
            margin-top: 1%;
        }
        .work-text{
            color:white;
            font-size: 4vw;
            font-style: oblique;
            padding: 5%;
            margin-top: 3%;
            background-color: #24465c;
            border-radius: 30px;
        }

        .register{
            color:green;
        }
        .button-content{
            display: grid;
            text-align: center;
            font-size: 4vw;
            width:300px;
            height: 100px;
            border-radius: 10px;
            margin-top: 3%;
        }
        .button-content:hover{
            background-color: rgb(6, 44, 31);
        }
        .logo{
        width: 60%;
        height: 30%;
        margin-left: auto;
        margin-right: auto;
        padding-top: 0%;
        margin-top: 0%;
         
      }
      .logobg{
          display: flex;
          flex-flow: column;
          justify-content:center;
      }
    .menu{
        text-align: center;
        color:#24465c;
        font-size: 4vw;
        font-style: oblique;
        padding: 0%;
        margin-top: 1%;
}
</style>
<head>
        <title>Detail</title>>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      </head>
      <body class="signin-bg">
     
            <div class="register-content">
                  <div class="logobg">
                          <img class="logo" src="../../img/logo.png">
                          <h1 class="sign-text">Information</h1>
                          
                          
                      </div>
<h1 class="sign-text">Hi {{ user.username }}</h1>
{% for temp in object_list %}
<div class="work-text">
<h4>Reserve ID: {{temp.id}}</h4>
<h4>Price :{{temp.cost}}</h4>
<h4>Type :{{temp.typearea}}</h4>
<h4>Size :{{temp.size}}</h4>
<h4>Address :{{temp.addresswork}}</h4>
<h4>Reserve date: {{temp.datework}}</h4>
<h4>Maid ID :{{temp.maid_id}}</h4>
</div>
{% endfor %}
<button class="button-content" ><a style="color: white;text-decoration:unset;" href="{% url 'slipform' %}">Upload Slip</a></button>
</div>
</body>
</html>

projectDjango/customer/templates/display_maid.html
html>
<style>
        input[type=text], select ,button{
                width: 100%;
                padding: 22px 20px;
                margin: 8px 0;
                display: inline-block;
                border: 1px solid #ccc;
                border-radius: 4px;
                box-sizing: border-box;
                padding: 10px;
                margin: 5px;
                font-size: 2vw;
        }
        input[type=email], select ,button{
                width: 100%;
                padding: 22px 20px;
                margin: 8px 0;
                display: inline-block;
                border: 1px solid #ccc;
                border-radius: 4px;
                box-sizing: border-box;
                padding: 10px;
                margin: 5px;
                font-size: 3vw;
        }
        input[type=file]{
            
                font-size: 3vw;
               
        }
        input[type=password], select ,button{
                /* width: 100%;
                padding: 12px 20px;
                margin: 8px 0; */
                display: inline-block;
                border: 1px solid #ccc;
                border-radius: 4px;
                box-sizing: border-box;
                padding: 10px;
                margin: 5px;
        }
        input[type=submit] ,button{
                width: 300px;
                background-color: #24465c;
                color: white;
                padding: 14px 20px;
                margin-left: 25%;
                margin-right: auto;
                border: none;
                /* border-radius: 4px; */
                cursor: pointer;
                
                
        }
        
        input[type=submit]:hover,button:hover {
                background-color: rgb(6, 44, 31);
        }
        
        .register-content {
                border-radius: 5px;
                background-color:rgba(255, 255, 255, 0.87);
                padding: 50px;
                margin-left: auto;
                margin-right: auto;
                margin-top: 20%;
                width: 80%;
                height:100%;
                padding-bottom: 100%;

                
                
        }
        .signin-bg{
                background-image: url("../../img/bg.jpg");
                background-repeat: no-repeat;
                background-size: cover;
                padding-bottom:90%;
                
        }
        .sign-text{
                text-align: center;
                color:#24465c;
                font-size: 5vw;
                font-style: oblique;
                padding: 0%;
                margin-top: 1%;
        }
        .work-text{
            color:white;
            font-size: 4vw;
            font-style: oblique;
            padding: 5%;
            margin-top: 3%;
            background-color: #24465c;
            border-radius: 30px;
            height: 280px;
        }

        .register{
                color:green;
        }
       
        .logo{
        width: 60%;
        height: 30%;
        margin-left: auto;
        margin-right: auto;
        padding-top: 0%;
        margin-top: 0%;
                
        }
        .logobg{
                display: flex;
                flex-flow: column;
                justify-content:center;
        }
        .menu{
        text-align: center;
        color:#24465c;
        font-size: 4vw;
        font-style: oblique;
        padding: 0%;
        margin-top: 1%;
        
}
.button-content{
                        display: grid;
                        text-align: center;
                        margin-left: 35%;
                        margin-top: 10%;
                        width:300px;
                        height: 150px;
                        border-radius: 20px;
                }
.button-maid{
        width: 200px;
        background-color: white;
        border:1px solid;
        border-radius: 10px;
        margin-left: 1%;
}

</style>
<head>
<title>Profile</title>>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body class="signin-bg">
                   
                    
                         
 <div class="register-content">
        <div class="logobg">
                <img class="logo" src="../../img/logo.png">
                <h1 class="sign-text">View Maid</h1>
        </div>
        
{% load static %}
<h1 class="sign-text">Hi {{ user.username}}</h1>

        {% for maid in maid_list %}
        <div class="work-text">
                <img src="{{ maid.image_maid.url }}"  width="260px" height="280px" style="float: left;margin-right: 3%;">
                <p ><a >Name: {{ maid.user.first_name }}   {{ maid.user.last_name }} </a></p> 
                <p>Tel:{{ maid.telephone }}</p>
                <button class="button-maid"> <a href="../reservemaid/{{maid.id}}" style="color:#24465c; text-decoration: unset;">Choose    </a> </button>
        </div>
        
        {% empty %}
            <td>No articles yet.</td>
        {% endfor %}
</div>
        <!-- <button class="button-content"><a href="{% url 'reserve' %}" style="text-decoration: unset;color: white;">BACK TO RESERVE</a></button> -->

</div>

</body>
</html>

projectDjango/customer/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
        <style>
                input[type=text], select ,button{
                    /* width: 100%;
                    padding: 12px 20px;
                    margin: 8px 0; */
                    display: inline-block;
                    border: 1px solid #ccc;
                    border-radius: 4px;
                    box-sizing: border-box;
                    padding: 10px;
                    margin: 5px;
                }
                input[type=password], select ,button{
                    /* width: 100%;
                    padding: 12px 20px;
                    margin: 8px 0; */
                    display: inline-block;
                    border: 1px solid #ccc;
                    border-radius: 4px;
                    box-sizing: border-box;
                    padding: 10px;
                    margin: 5px;
                }
                input[type=submit] ,button{
                    width: 100px;
                    background-color: rgb(37, 19, 2);
                    color: white;
                    padding: 14px 20px;
                    margin-left: auto;
                    margin-right: auto;
                    border: none;
                    /* border-radius: 4px; */
                    cursor: pointer;
                    
                    
                }
                
                input[type=submit]:hover,button:hover {
                    background-color: rgb(6, 44, 31);
                }
                
                .signin-content {
                    border-radius: 5px;
                    background-color:rgba(255, 255, 255, 0.87);
                    padding: 50px;
                    margin-left: auto;
                    margin-right: auto;
                    margin-top: 30%;
                    width: 50%;
                    height:100%;
        
                    
                    
                }
                .signin-bg{
                    background-image: url("../../img/bg.jpg");
                    background-repeat: no-repeat;
                    background-size: cover;
                    padding-bottom:90%;
                    
                }
                .sign-text{
                    text-align: center;
                    color:#24465c;
                    font-size: 5vw;
                    font-style: oblique;
                    padding: 0%;
                    margin-top: 1%;
                }
        
                .register{
                    color:green;
                }
                .button-content{
                    display: grid;
                    text-align: center;
                }
                .logo{
                width: 70%;
                height: 80%;
                margin-left: auto;
                margin-right: auto;
                padding-top: 0%;
                margin-top: 0%;
                 
              }
              .logobg{
                  display: flex;
                  flex-flow: column;
                  justify-content:center;
              }
                      </style>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Sign In</title>
   
</head>

<body class="signin-bg">
   
    <div class="signin-content">
            <div class="logobg">
                    <img class="logo" src="../../img/logo.png">
                    
                    
                </div>
                <h1 class="sign-text">Sign in </h1>
            <form role="form" method="post" action="">
                {% csrf_token %}
                <table style="margin: auto">
                    <tr>
                    <!-- <div class="form-group"> -->
                        <td>{{ form.username.label_tag }}</td>
                        <td><input class="" placeholder="Username" name="username" type="text" autofocus></td>
                        <!-- </div> -->
                    </tr>
                    <tr>
                    <!-- <div class="form-group"> -->
                        <td>{{ form.password.label_tag }}</td>
                        <td><input class="" placeholder="Password" name="password" type="password" value=""></td>
                        <!-- </div> -->
                    </tr>
                </table>
                <div class="button-content">
                    <input type="submit" class="btn btn-lg btn-success btn-block" value="Login">
                    <a class="register" href="{% url 'signup' %}">Register</a>
                </div>
            </form> 
        </div>           
      <!-- <div class="button-content">
        
        <input type="submit" value="login" />
        <input type="hidden" name="next" value="{{ next }}" />
        <a class="register" href="{{'register.html'}}">Register</a>
      </div> -->
  </div>
</body>

</html> 

projectDjango/customer/templates/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/mysty.css' %}"> -->
  <title>Register</title>
  <style>
        input[type=text], select ,button{
              width: 100%;
              padding: 12px 20px;
              margin: 8px 0;
              display: inline-block;
              border: 1px solid #ccc;
              border-radius: 4px;
              box-sizing: border-box;
              padding: 10px;
              margin: 5px;
          }
          input[type=password], select ,button{
              width: 100%;
              padding: 12px 20px;
              margin: 8px 0;
              display: inline-block;
              border: 1px solid #ccc;
              border-radius: 4px;
              box-sizing: border-box;
              padding: 10px;
              margin: 5px;
          }
          input[type=email], select ,button{
              width: 100%;
              padding: 12px 20px;
              margin: 8px 0;
              display: inline-block;
              border: 1px solid #ccc;
              border-radius: 4px;
              box-sizing: border-box;
              padding: 10px;
              margin: 5px;
          }
          input[type=submit] ,button{
              width: 100px;
              text-align: center;
              background-color: rgb(37, 19, 2);
              color: white;
              padding: 14px 20px;
              margin-left: 30%;
              margin-right: auto;
              border: none;
              /* border-radius: 4px; */
              cursor: pointer;
              
              
          }
          
          input[type=submit]:hover,button:hover {
              background-color: rgb(6, 44, 31);
  
          }
          
          .register-content {
              border-radius: 5px;
              background-color:rgba(255, 255, 255, 0.87);
              padding: 5%;
              margin-left: auto;
              margin-right: auto;
              margin-top: 10%;
              width: 70%;
              height:100%;
  
              
              
          }
          .signin-bg{
              background-image: url("../../img/bg.jpg");
              background-repeat: no-repeat;
              background-size: cover;
              padding-bottom:60%;
              
          }
          .sign-text{
              text-align: center;
              color:#24465c;
              font-size: 5vw;
              font-style: oblique;
              padding: 0%;
              margin-top: 1%;
          }
          .work-text{
              color:white;
              font-size: 4vw;
              font-style: oblique;
              padding: 5%;
              margin-top: 3%;
              background-color: #24465c;
              border-radius: 30px;
          }
  
          .register{
              color:green;
          }
          .button-content{
              display: grid;
              text-align: center;
          }
          .logo{
          width: 70%;
          height: 80%;
          margin-left: auto;
          margin-right: auto;
          padding-top: 0%;
          margin-top: 0%;
           
        }
        .logobg{
            display: flex;
            flex-flow: column;
            justify-content:center;
        }
      .menu{
          text-align: center;
          color:#24465c;
          font-size: 4vw;
          font-style: oblique;
          padding: 0%;
          margin-top: 1%;
      }
      </style>
</head>
<body class="signin-bg">
    <div class="register-content">
            
        {% block content %}
        <div class="register-content">
                <div class="logobg">
                <img class="logo" src="../../img/logo.png">
                <h1 class="sign-text">Sign up</h1>
                
                
            </div>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Sign up</button>
        </form>
      {% endblock %}
    </div>
    
</body>
</html>